FROM ubuntu

WORKDIR /ImageExtract
COPY . .

RUN apt update
RUN apt install python3 pip -y
RUN pip install -r ./requirements.txt
RUN echo '$APIHOST'
CMD ["python3", "textExtractor.py", "--host", "0.0.0.0"]
EXPOSE 8080


